version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    working_directory: ~/College_Management_System
    docker:
      - image: cimg/ruby:3.3.1-node
    steps:
      - checkout
      - run:
          name: Install Dependencies for Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget apt-transport-https fonts-liberation \
              libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcups2 libgtk-3-0 \
              libnspr4 libnss3 libu2f-udev libvulkan1 libxcomposite1 libxdamage1 \
              xdg-utils
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
            google-chrome --version
      - run:
          name: Install Xvfb
          command: sudo apt install -y xvfb
      - run:
          name: Start Xvfb
          command: Xvfb :99 -ac &
          background: true
      - run:
          name: Install Ruby and JavaScript Dependencies
          command: |
            bundle install
            yarn install
      - run:
          name: Setup ChromeDriver
          command: |
            CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
            CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
            wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
            sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
      - run:
          name: Check versions
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Run Tests
          command: |
            export DISPLAY=:99
            bundle exec rspec

  deploy:
    docker:
      - image: cimg/ruby:3.3.1-node
    steps:
      - run:
          name: Deploy Application
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "
            sudo rm -rf College_Management_System/;
            sudo git clone https://github.com/YagoTaira/College_Management_System.git;
            cd College_Management_System;
            sudo dos2unix deploy.sh;
            source deploy.sh;
            "
