version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build: # Defines a job named 'build'
          filters:
            branches:
              only:
                - main # Execute this job only when code is pushed to the 'main' branch.
      - deploy: # Defines a job named 'deploy'
          filters:
            branches:
              only:
                - main # Execute this job only when code is pushed to the 'main' branch.
          requires:
            - build # Ensures the 'deploy' job runs only after the 'build' job succeeds

jobs:
  build:
    working_directory: ~/College_Management_System
    docker:
      - image: cimg/ruby:3.3.1-node
    steps:
      - checkout
      - run:
          name: Install Google Chrome
          command: |
            # Install Chrome
            sudo apt update
            sudo apt install google-chrome-stable

            # Verify Installation
            google-chrome --version
      - run:
          name: Install ChromeDriver
          command: |
            # Download ChromeDriver
            npx @puppeteer/browsers install chromedriver@126.0.6478.126

            # Remove bin directory
            sudo rm -rf ~/bin

            # Create bin directory
            mkdir ~/bin

            # Move chromdriver to bin folder
            sudo mv /home/circleci/College_Management_System/chromedriver/linux-126.0.6478.126/chromedriver-linux64/chromedriver ~/bin/chromedriver

            # Add permission to execute chromedriver
            chmod +x ~/bin/chromedriver

            # Add PATH
            export PATH="$HOME/bin:$PATH"

            # Apply changes
            source ~/.bashrc

            # Verify installation
            chromedriver --version
      - run:
          name: Install Xvfb
          description: Run server wihout display
          command: |
            sudo apt install xvfb
      - run:
          name: Install dependencies
          command: |
            bundle install
            yarn install
      - run:
          name: Run tests without display
          command: xvfb-run rspec
  deploy:
    docker:
      - image: cimg/ruby:3.3.1-node
    steps:
      - run:
          name: deploy-application
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "
              sudo rm -rf College_Management_System/;
              sudo git clone https://github.com/YagoTaira/College_Management_System.git;
              cd College_Management_System;
              sudo dos2unix deploy.sh;
              source deploy.sh;
            "
